# projects/risk-equity-adaptive/environment.yml

name: risk_equity_adaptive_env
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  # --- Conda packages ---
  - python
  - pandas
  - pydantic
  - ruff
  - mypy
  - networkx
  - matplotlib
  - cartopy
  - seaborn
  - pip

  # --- Pip packages ---
  - pip:
      - contextily
